version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=data
    ports:
      - 3306:3306
    container_name: mysqldb
    healthcheck:
      test: ['CMD','mysqladmin','ping','-h','localhost']
      timeout: 10s
      retries: 10
    networks:
      - custom-network
  myapp:
    build:
      context: ./Backend  
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DB=data
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    networks:
      - custom-network    
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - custom-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge