CREATE TABLE IF NOT EXISTS tasks (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userId` INT UNSIGNED NOT NULL,
  `days` INT UNSIGNED NOT NULL,
  `minimumRating` INT UNSIGNED NOT NULL,
  `maximumRating` INT UNSIGNED NOT NULL, 
  `retries` INT UNSIGNED NOT NULL DEFAULT 3,
  `scheduledAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pickedAt` TIMESTAMP,
  `executedAt` TIMESTAMP,

  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES users(`id`)
);